# Generated by Django 4.1.3 on 2024-02-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=300)),
                ('party_description', models.CharField(max_length=1000)),
                ('discord_link', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('image_url', models.CharField(max_length=500)),
                ('bio', models.CharField(max_length=1000)),
                ('uid', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=300)),
                ('show_description', models.CharField(max_length=20)),
                ('show_poster', models.CharField(max_length=500)),
                ('is_watching', models.BooleanField()),
                ('show_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.showgenre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='PartyAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.user'),
        ),
        migrations.AddField(
            model_name='party',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchpartyapi.show'),
        ),
    ]
