# Generated by Django 4.1.3 on 2024-02-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchpartyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_description',
            field=models.CharField(max_length=1000),
        ),
    ]
